---
- hosts: 10.10.20.100
  connection: network_cli
  remote_user: admin
  become: yes
  become_method: enable
  tasks:
    - name: run show version on remote devices
      ios_command:
        commands: show runn
