#simple IOS config in ansible
---
- name: Sample IOS config for Ansible 2.5+
  hosts:
    - sandbox-iosxe-latest-1.cisco.com
    - sandbox-iosxe-recomm-1.cisco.com
  gather_facts: false
  vars_prompt:
    - name: loopback_num
      prompt: "What Loopback Number to Configure?"
      private: no
    - name: loopback_ip
      prompt: "What IP address to use? Example 192.168.1.1/32"
      private: no

  tasks:
    - name: Test
      ios_interfaces:
        config:
          - name: Loopback{{loopback_num}}
            enabled: True
            description: Created with Ansible
    - name: Assign IP to loopback
      ios_l3_interfaces:
        config:
          - name: Loopback{{loopback_num}}
            ipv4:
              - address: "{{loopback_ip}}"