#simple IOS config in ansible
---
- name: Sample IOS config for Ansible 2.5+
  hosts:
    - sandbox-iosxe-latest-1.cisco.com
    - sandbox-iosxe-recomm-1.cisco.com
  gather_facts: false
  vars_prompt:
    - name: loopback_num
      prompt: "What Loopback Number to Delete?"
      private: no

  tasks:

  - name: Delete loopback {{loopback_num}}
    ios_interfaces:
      config:
        - name: Loopback{{loopback_num}}
      state: purged